### ISSUE TITLE
Создать макет

### ISSUE THREAD

**Issue by Winterpuma** [Winterpuma/bmstu_team-development#4]
Создать макет игры. 

- [x] Главное меню
- [x] Игра 
- [x] Меню выбора уровня
- [x] Об авторах

В комментариях прикрепить макеты в виде изображений.
Главное меню должно содержать кнопки "New game", "Level selection", "About authors", "Exit".
Игра содержит примерное изображение игрока, NPC и платформ.
Меню выбора уровня содержит кнопки с номерами уровней.
Страница об авторах игры содержит информацию о каждом участнике и фото.

**Comment by anastasialavrova** [comment]
Меню игры

![image](https://user-images.githubusercontent.com/44167571/112769989-fe0a9800-902c-11eb-854c-0ddb127cd1f4.png)

**Comment by anastasialavrova** [comment]
Игра

![image](https://user-images.githubusercontent.com/44167571/112770000-124e9500-902d-11eb-8182-e46038ddc410.png)

**Comment by anastasialavrova** [comment]
Меню выбора уровня

![image](https://user-images.githubusercontent.com/44167571/112770014-25f9fb80-902d-11eb-8afe-0eba2e0a821d.png)

**Comment by anastasialavrova** [comment]
Информация об авторах

![image](https://user-images.githubusercontent.com/44167571/112770022-34481780-902d-11eb-8625-a9e1be398133.png)
