### ISSUE TITLE
Найти ресурс-паки для игры

### ISSUE THREAD

**Issue by Winterpuma** [Winterpuma/bmstu_team-development#5]
Найти ресурс-паки (assert) для дальнейшего использования. Должны как минимум содержать спрайты игрока, NPC, платформы, фон, кнопки.

**Comment by UselessSaint** [comment]
Ассеты от одного создателя:
https://assetstore.unity.com/packages/2d/characters/pixel-adventure-1-155360
https://assetstore.unity.com/packages/2d/characters/pixel-adventure-2-155418

Основные интересные ассеты в 1ом паке, но думаю можно найти что-то интересное и во 2ом

**Comment by anastasialavrova** [comment]
Еще интересные ассеты:

https://assetstore.unity.com/packages/2d/characters/simple-2d-platformer-assets-pack-188518#content
https://assetstore.unity.com/packages/2d/textures-materials/tiles/grotto-escape-pack-54254#content
