### ISSUE TITLE
Обучение Unity

### ISSUE THREAD

**Issue by Winterpuma** [Winterpuma/bmstu_team-development#9]
Каждый должен ознакомиться с принципом создания игр на Unity, потренироваться в unity-platformer-tutorial. 

В эту задачу входит установка unity, поиск обучающих материалов и похожих проектов.

**Comment by anastasialavrova** [comment]
Целый плейлист на Youtube, посвященный обучению Unity:

https://www.youtube.com/playlist?list=PLPV2KyIb3jR5QFsefuO2RlAgWEz6EvVi6

**Comment by Winterpuma** [comment]
Бесплатная лицензия для студентов у Unity. + оформление github student dev pack
https://store.unity.com/ru/academic/unity-student
https://education.github.com/pack
